/**
 * Offline companion creation — builds a SillyTavern-compatible card from the
 * deterministic persona generator when the LLM pipeline is unavailable
 * (no DEEPSEEK_API_KEY, network failure, or schema errors).
 */

import { generatePersona } from "./persona";
import type { CharacterCard, CreationInput } from "@/types/character-card";

export function offlineCard(input: CreationInput): CharacterCard {
  const persona = generatePersona({
    archetype: input.archetype,
    vibe: input.vibe,
  });

  return {
    spec: "chara_card_v2",
    spec_version: "2.0",
    name: persona.name,
    description: [
      persona.backstory,
      `Personality: ${persona.personality.join(", ")}`,
      `Speech: ${persona.speechStyle}`,
      `Tagline: ${persona.tagline}`,
    ].join("\n\n"),
    personality: persona.personality.join(", "),
    scenario: persona.openingLine,
    first_mes: persona.openingLine,
    mes_example: "",
    creator_notes: `Generated by Everheart offline engine (archetype: ${input.archetype}).`,
    system_prompt: `You are ${persona.name}, age ${persona.age}. Stay fully in character; never break the fourth wall; reply in 2-4 sentences. Speech style: ${persona.speechStyle}. This is a demo build: keep content non-explicit and tasteful. Do not mention being an AI.`,
    post_history_instructions:
      "Continue the scene naturally. Remember previous details.",
    tags: [input.archetype.toLowerCase()],
    everheart: {
      age: persona.age,
      isNsfw: false,
      relationshipDynamic: persona.tagline,
    },
  };
}
